"""Optional Tkinter Canvas renderer for GUI waypoint map data.

This is an example renderer.  Existing GUI code can copy only the parts it needs.
It expects gui_data generated by PlannerWaypointMapSource.build() or
PlannerWaypointMapSource.build_from_task().
"""

from __future__ import annotations

from typing import Any, Dict

from .gui_map_source import world_to_canvas_transform


STATION_TYPE_NAMES = {
    1: 'STORAGE',
    2: 'WORKBENCH',
    3: 'CUSTOMER',
    4: 'HYBRID',
}


def draw_waypoint_map(canvas, gui_data: Dict[str, Any]) -> None:
    """Draw station goals, waypoint paths, and station materials on a Canvas.

    canvas:
        tkinter.Canvas-like object.

    gui_data:
        Dict returned by PlannerWaypointMapSource.
    """
    canvas.delete('all')

    width = int(canvas.winfo_width() or 800)
    height = int(canvas.winfo_height() or 600)
    to_canvas = world_to_canvas_transform(gui_data.get('bounds', {}), width, height)

    # 1) Draw waypoint approach paths first.
    for station in gui_data.get('stations', []):
        path = station.get('path') or []
        if len(path) < 2:
            continue
        points = []
        for p in path:
            points.extend(to_canvas(p['x'], p['y']))
        canvas.create_line(*points, width=2, dash=(4, 3), tags='waypoint_path')

    # 2) Draw stations and current materials.
    for station in gui_data.get('stations', []):
        x, y = to_canvas(station['x'], station['y'])
        sid = int(station['station_id'])
        stype = station.get('station_type')
        stype_text = STATION_TYPE_NAMES.get(stype, str(stype) if stype is not None else '')
        materials = station.get('materials', []) or []

        r = 18
        canvas.create_oval(x - r, y - r, x + r, y + r, width=2, tags=f'station_{sid}')
        canvas.create_text(x, y, text=str(sid), tags=f'station_{sid}')
        canvas.create_text(
            x,
            y - 30,
            text=f'{station.get("name", "")}',
            tags=f'station_{sid}_label',
        )
        if stype_text:
            canvas.create_text(x, y + 31, text=stype_text, tags=f'station_{sid}_type')
        if materials:
            # Cargo/material display: this is the part that should change when
            # manager/task state says an item was loaded or unloaded.
            canvas.create_text(
                x,
                y + 48,
                text='[' + ', '.join(map(str, materials)) + ']',
                tags=f'station_{sid}_materials',
            )

    # 3) Draw origin/bounds label.
    bounds = gui_data.get('bounds', {})
    canvas.create_text(
        10,
        10,
        anchor='nw',
        text=f"waypoint map bounds: {bounds}",
        tags='map_info',
    )
